### ISSUE TITLE
Dubious assumption in lexer.c

### ISSUE THREAD

**Issue by mingodad** [dibyendumajumdar/ravi-compiler#19]
In lexer.c::raviX_create_string there is a test to see if we passed the reserved words:
```
for (int i = 0; i < ARRAY_SIZE(luaX_tokens); i++) {
			if (luaX_tokens[i][0] == '<')
				break; // We have gone past reserved keywords
			if (strcmp(luaX_tokens[i], s) == 0) {
				new_string->reserved = i; /* save index of the keyword */
				break;
			}
		}
```
And this is the actual keyword list:
```
static const char *const luaX_tokens[] = {
    "and",	 "break",  "do",      "else",	  "elseif", "end",	"false",     "for",	"function",
    "goto",	 "if",	   "in",      "local",	  "defer",  "nil",	"not",	     "or",	"repeat",
    "return",	 "then",   "true",    "until",	  "while",  "//",	"..",	     "...",	"==",
    ">=",	 "<=",	   "~=",      "<<",	  ">>",	    "::",	"@integer",  "@number", "@integer[]",
    "@number[]", "@table", "@string", "@closure", "<eof>",  "<number>", "<integer>", "<name>",	"<string>"};
```
The test `if (luaX_tokens[i][0] == '<')` doesn't seem to be correct probably `if (luaX_tokens[i][0] == '/')` is what we want ?

**Comment by mingodad** [comment]
Or if the intention is to consider `@*` as keywords then moving the function lexer.c::raviX_create_string bellow the `ctype` functions and do a test like:
```
for (int i = 0; i < ARRAY_SIZE(luaX_tokens); i++) {
			if (lislalpha(luaX_tokens[i][0]) || luaX_tokens[i][0] == '@') {
			  if (strcmp(luaX_tokens[i], s) == 0) {
				new_string->reserved = i; /* save index of the keyword */
				break;
			  }
                       }
		}
```

**Comment by dibyendumajumdar** [comment]
Thank you - you are correct the code is wrong. The intention was to detect <eof>.

**Comment by dibyendumajumdar** [comment]
Reserved is a misnomer really, as not all the tokens are keywords. You can think of it like this: the reserved tokens are those that have enum defined in `enum TokenType` except tokens that need an associated literal - i.e. those that are after the `TOK_EOS`.
