### ISSUE TITLE
Incorporate the ryu library to convert doubles to strings

### ISSUE THREAD

**Issue by dibyendumajumdar** [dibyendumajumdar/ravi-compiler#71]

**Comment by data-man** [comment]
Try this: https://github.com/ibireme/c_numconv_benchmark/tree/master/vendor/yy_double :)

**Comment by dibyendumajumdar** [comment]
hi @data-man 

thank you for the reference, interesting. but I use the conversion in code gen so absolute performance is not the main issue.
