### ISSUE TITLE
Bugs Reports:

### ISSUE THREAD

**Issue by An0nyMooUS** [dibyendumajumdar/ravi-compiler#86]
- emit_op_cbr: Unexpected pseudo
```
if test:GetIsRight() then -- only works if ``== true`` explicitly.
   -- emit_op_cbr: Unexpected pseudo: T(1..)
end
```

**Comment by dibyendumajumdar** [comment]
hi @An0nyMooUS  please check if this now works

**Comment by An0nyMooUS** [comment]
> hi @An0nyMooUS please check if this now works

Works. But i find another bug:

[crazylua.txt](https://github.com/dibyendumajumdar/ravi-compiler/files/9649555/crazylua.txt)

```
Damage[T
input(4252): unexpected symbol near '='
```

**Comment by An0nyMooUS** [comment]
Scripts with many tables may return this

``input(1851): unexpected symbol near '}'``

**Comment by dibyendumajumdar** [comment]
hi @An0nyMooUS - I assume that the problem with crazylua.txt occurred on Windows? I have pushed a fix that should solve it.

**Comment by An0nyMooUS** [comment]
> hi @An0nyMooUS - I assume that the problem with crazylua.txt occurred on Windows? I have pushed a fix that should solve it.

I haven't tested it on linux. I'm currently using Windows. :)
